name: Build ZeldaWindWakerTrainer

on:
  push:
    branches:
      - main # Veya projenizin ana dalı (master)
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest # Bu trainer Windows üzerinde çalıştığı için Windows ortamı seçmek mantıklı.

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET Core 3.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '3.0.x' # Trainer'ın ihtiyaç duyduğu .NET Core sürümü

    - name: Install Visual C++ Redistributable 2015
      run: |
        # Visual C++ Redistributable'ı indirip kurmak için komutlar
        # Bu adımın nasıl yapılacağı platforma göre değişir.
        # Genellikle sessiz kurulum (silent installation) parametreleri kullanılır.
        # Örneğin: Start-Process -Wait -FilePath "vc_redist.x64.exe" -ArgumentList "/install /quiet /norestart"
        # Veya bir PowerShell betiği çalıştırabilirsiniz.
        # Kesin indirme bağlantısı ve sessiz kurulum parametreleri için Microsoft'un resmi kaynaklarına bakmanız gerekir.
        echo "Visual C++ Redistributable kurulumu için manuel adım gerekiyor veya script yazılması gerekli."

    - name: Build Solution
      run: dotnet build --configuration Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ZeldaWindWakerTrainer
        path: bin/Release/netcoreapp3.0/ # Oluşturulan yürütülebilir dosyanın yolu
